function bar(t){try{foo()}catch(o){alert("Exception caught (foo not defined)")}alert(t)}bar(10);